# Generated by Django 3.2.14 on 2022-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='place',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
