# Generated by Django 3.2.14 on 2022-08-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_city_place'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Consultant',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='city',
            new_name='consultant',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='country',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='country',
            new_name='department',
        ),
    ]
